name: MODIS Indonesia Processing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

jobs:
  modis-processing:
    runs-on: ubuntu-latest
    env:
      MODIS_USER: ${{ secrets.MODIS_USER }}
      MODIS_PASS: ${{ secrets.MODIS_PASS }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          pip install numpy rasterio pymodis geopandas requests dotenv

      - name: Run MODIS Processing
        run: python process_modis_indonesia.py

      - uses: actions/upload-artifact@v4
        with:
          name: stacked_modis_indonesia
          path: modis_data/stacked_ndvi_evi_indonesia.tif
